export type ResponseCodeKeys =
  // middleware/authMiddleware
  | "authentication/noTokenProvided"
  | "authentication/tokenExpired"
  | "authentication/tokenFailed"
  // controllers/users
  | "verification/userNotFound"
  | "verification/success"
  | "verification/error"
  | "tokensRenewal/noRefreshToken"
  | "tokensRenewal/success"
  | "tokensRenewal/error"
  | "signUp/fieldsValidationError"
  | "signUp/success"
  | "signUp/error"
  | "signIn/fieldsValidationError"
  | "signIn/success"
  | "signIn/error"
  // controllers/friends
  | "getFriendSuggestions/success"
  | "getFriendSuggestions/error"
  | "postFriendRequest/friendshipAlreadyExists"
  | "postFriendRequest/friendRequestPending"
  | "postFriendRequest/requestRenewalSuccess"
  | "postFriendRequest/requestSuccess"
  | "postFriendRequest/requestError"
  | "getFriendRequests/success"
  | "getFriendRequests/error"
  | "patchFriendRequest/notFound"
  | "patchFriendRequest/noAuthorizedRecipient"
  | "patchFriendRequest/alreadyResponded"
  | "patchFriendRequest/success"
  | "patchFriendRequest/error"
  // controllers/currencies
  | "getCurrencies/success"
  | "getCurrencies/error"
  | "getCurrencyRate/invalid-params"
  | "getCurrencyRate/success"
  | "getCurrencyRate/error"
  // controllers/groups
  | "getGroupList/success"
  | "getGroupList/error"
  | "postGroup/invalid-currency"
  | "postGroup/success"
  | "postGroup/error"
  | "getGroupRequests/success"
  | "getGroupRequests/error"
  | "patchGroupRequest/not-found"
  | "patchGroupRequest/success"
  | "patchGroupRequest/error";

export default function Index() {
  return null;
}
